### ISSUE TITLE
ModuleNotFoundError: No module named 'hikvisionapi

### ISSUE THREAD

**Issue by theduc219** [SinonApp/cansleep#3]
ModuleNotFoundError: No module named 'hikvisionapi

**Comment by seisdr** [comment]
`
pip install hikvisionapi
`

**Comment by Kittyskj** [comment]
pip3 install -r requirements.txt

before use programm install all requirements

**Comment by theduc219** [comment]
Already installed but still error message

**Comment by theduc219** [comment]
Requirement already satisfied: h11<0.15,>=0.13 in /home/kbb/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx->hikvisionapi) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /home/kbb/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx->hikvisionapi) (3.7.0)
Requirement already satisfied: exceptiongroup in /home/kbb/.local/lib/python3.10/site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx->hikvisionapi) (1.1.1)
kbb@kbb-HP-Notebook:~/cansleep$ sudo python3 cansleep.py -h
Traceback (most recent call last):
  File "/home/kbb/cansleep/cansleep.py", line 6, in <module>
    from tools.brute import rtsp_bruter, dahua_bruter, hikka_bruter
  File "/home/kbb/cansleep/tools/brute.py", line 3, in <module>
    from connectors.hikvision import HikClient
  File "/home/kbb/cansleep/connectors/hikvision.py", line 1, in <module>
    from hikvisionapi import Client
ModuleNotFoundError: No module named 'hikvisionapi'
